language: generic
sudo: required
services:
 - docker

before_install:
 - doceker build -t naruchitwates/my-docker-react -f Dockerfile.dev . 

script:
 - docker run -e CI=true -t naruchitwates/my-docker-react npm run test -- --coverage